// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ssezibwijzevjfikyzzm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNzZXppYndpanpldmpmaWt5enptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIxNTM1MTIsImV4cCI6MjA3NzcyOTUxMn0.qEOFYxtWpum4ChT_pOLsSLW0Xc-61oPZuK2CShgyPR0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);